### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by ghost** [pidpawel/wigle-visualizer#1]
Hey,
When I downloaded and execute your python code I got this error : 
```
Traceback (most recent call last):
  File "./webapp.py", line 121, in <module>
    record_container.parse_file(csv_filename)
  File "./webapp.py", line 48, in parse_file
    with open(filename) as csvfile:
FileNotFoundError: [Errno 2] No such file or directory: 'WigleWifi_20140828192242.csv'
```
Thanks :)

**Comment by ghost** [comment]
I solved the problem.
We need to create a file called "WigleWifi_20140828192242.csv", so you have to execute : 
`touch WigleWifi_20140828192242.csv`
In the project folder.
